Game = window.TTT.Game
g = new Game(3)
g.printBoard()
g.takeTurn([0,0])
g.printBoard()
g.takeTurn([0,1])
g.printBoard()
g.takeTurn([1,0])
g.printBoard()
g.takeTurn([0,2])
g.printBoard()
g.takeTurn([2,0])
g.printBoard()
